apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: mysql
    app: demo
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: mysql
        app: demo
    spec:
      hostname: mysql
      containers:
      - image: mysql:5.7.25
        name: mysql
        ports:
          - containerPort: 3306         
            protocol: TCP
        env: 
          - 
            name: "MYSQL_ROOT_PASSWORD"
            value: "password"

        resources: {}
status: {}
